//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFrame.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XFrame.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected source content is empty..
        /// </summary>
        public static string EmptyContentMessage {
            get {
                return ResourceManager.GetString("EmptyContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty transformation result.
        /// </summary>
        public static string EmptyTransformationMessage {
            get {
                return ResourceManager.GetString("EmptyTransformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Samples Error.
        /// </summary>
        public static string ErrorLoadSamples {
            get {
                return ResourceManager.GetString("ErrorLoadSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to export. Run a transformation first..
        /// </summary>
        public static string ExportEmptyMessage {
            get {
                return ResourceManager.GetString("ExportEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Error.
        /// </summary>
        public static string ExportErrorTitle {
            get {
                return ResourceManager.GetString("ExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved: {0}.
        /// </summary>
        public static string ExportSuccessMessage {
            get {
                return ResourceManager.GetString("ExportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;{0}&apos; tags found in the selected source..
        /// </summary>
        public static string NoTagsFoundMessage {
            get {
                return ResourceManager.GetString("NoTagsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load XML file..
        /// </summary>
        public static string SelectXmlErrorTitle {
            get {
                return ResourceManager.GetString("SelectXmlErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load XSLT file..
        /// </summary>
        public static string SelectXsltErrorTitle {
            get {
                return ResourceManager.GetString("SelectXsltErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw XML.
        /// </summary>
        public static string SourceRawXml {
            get {
                return ResourceManager.GetString("SourceRawXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformed Result.
        /// </summary>
        public static string SourceTransformedXml {
            get {
                return ResourceManager.GetString("SourceTransformedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Sum Error.
        /// </summary>
        public static string SumErrorTitle {
            get {
                return ResourceManager.GetString("SumErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic sum was added to the {0} tag..
        /// </summary>
        public static string SumResultMessage {
            get {
                return ResourceManager.GetString("SumResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags Error.
        /// </summary>
        public static string TagsErrorTitle {
            get {
                return ResourceManager.GetString("TagsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags Found.
        /// </summary>
        public static string TagsFoundTitle {
            get {
                return ResourceManager.GetString("TagsFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLT Transformation Error.
        /// </summary>
        public static string TransformationFailedTitle {
            get {
                return ResourceManager.GetString("TransformationFailedTitle", resourceCulture);
            }
        }
    }
}
