<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8d3dcb7f-97db-4567-a1d1-778d637ddb1c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XFrame\XFrame.csproj">
      <SetTargetFramework>TargetFramework=net10.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>

</Project>
